### ISSUE TITLE
yarn error, both master and v1.4.2

### ISSUE THREAD

**Issue by pengwb9527** [AgoraIO-Usecase/AgoraMeetingExample-Electron#3]
Error output:
warning agora-electron-sdk > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning agora-electron-sdk > just-task > @types/chokidar@2.1.3: This is a stub types definition. chokidar provides its own type definitions, so you do not need this installed.
warning agora-electron-sdk > node-gyp > request > har-validator@5.1.5: this library is no longer supported
warning agora-electron-sdk > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning agora-electron-sdk > just-task > @rushstack/package-deps-hash > @rushstack/node-core-library > z-schema@5.0.6: has issues with node 14
warning agora-plugin > just-task > @rushstack/package-deps-hash > @rushstack/node-core-library > z-schema@5.0.6: has issues with node 14
warning agora-plugin > node-gyp > make-fetch-happen > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
error /root/AgoraMeetingExample-Electron-1.4.2/src/node_modules/agora-electron-sdk: Command failed.
Exit code: 1
Command: just install
Arguments: 
Directory: /root/AgoraMeetingExample-Electron-1.4.2/src/node_modules/agora-electron-sdk
Output:
[10:10:30 AM] ■ started 'install'
[10:10:30 AM] x Unsupported platform!
[10:10:30 AM] x Error detected while running 'install'
[10:10:30 AM] x ------------------------------------
[10:10:30 AM] x Error: Unsupported platform!
    at genOS (/root/AgoraMeetingExample-Electron-1.4.2/src/node_modules/agora-electron-sdk/scripts/download.js:23:13)
    at module.exports (/root/AgoraMeetingExample-Electron-1.4.2/src/node_modules/agora-electron-sdk/scripts/download.js:32:70)
    at /root/AgoraMeetingExample-Electron-1.4.2/src/node_modules/agora-electron-sdk/just-task.js:142:5
    at _wrapFunction (/root/AgoraMeetingExample-Electron-1.4.2/src/node_modules/agora-electron-sdk/node_modules/just-task/lib/wrapTask.js:15:36)
    at install (/root/AgoraMeetingExample-Electron-1.4.2/src/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:421:15)
    at runBound (domain.js:432:12)
    at asyncRunner (/root/AgoraMeetingExample-Electron-1.4.2/src/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[10:10:30 AM] x ------------------------------------
[10:10:30 AM] x Error previously detected. See above for error messages.
  failedTask=installAppDeps stackTrace=Error: /usr/bin/node exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by pengwb9527** [comment]
node -v
v14.21.3

 yarn -v
1.22.19

cmake --version
cmake version 3.27.5
